#!ruby

while l = $stdin.gets
  d = l.chomp.encode("UTF-32LE")
  while !(piece = d.slice!(0...5)).empty?
    a = piece.unpack("V*")
    a.map! do |x|
      if x < 0x10000
        "\\\\u%04x" % x
      else
        "\\\\U%08x" % x
      end
    end
    puts "\"#{a.join}\"  /* #{piece.encode("UTF-8")} */"
  end
end
